application:
  mqtt:
    protocol: "${MQTT_PROTOCOL:tcp}"
    host: "${MQTT_HOST:localhost}"
    port: "${MQTT_PORT:1883}"
    topic: "${MQTT_TOPIC:HEALTH}"
  camunda:
    dmnFileResourcePath: triage.dmn


server:
  port: "${INTERNAL_SERVICE_PORT:8080}"

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST}/postgres"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
